---
resources:
- name: source-code
  type: git
  source:
    branch: master
    uri: https://github.com/liangboyi/concourse-demo-web
- name: cloudfoundry
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: unit-test-web
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: unit-test
    file: concourse/tasks/unit-test-web.yml
- name: deploy-web
  public: true
  plan:
  - get: source-code
    trigger: true
    passed:
      - unit-test-web
  - task: package
    file: source-code/concourse/tasks/package-web.yml
  - put: cloudfoundry
    params:
      manifest: source-code/manifest/concourse-demo-web-manifest.yml
      path: target-web/concourse-demo-web.jar
