platform: linux

image_resource:
  type: docker-image
  source:
    repository: https://hub.docker.com/jdk8maven
    tag: "rickeysu/jdk8maven:v1"
    insecure_registries: ["https://hub.docker.com/"]
inputs:
- name: source-code

outputs:
- name: target-web

run:
  path: source-code/concourse/tasks/package-web.sh
